# Generated by Django 3.0.8 on 2020-07-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200710_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
